# This docker compose file runs dependencies for
# DEV or test environment
services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "30101:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  db-ui:
    image: adminer
    ports:
      - "30104:8080"
  redis:
    image: redis
    ports:
      - "30102:6379"
volumes:
  db_data:
