//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ImageParentTable = newImageParentTableTable("public", "image_parent_table", "")

type imageParentTableTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	ImageID          postgres.ColumnString
	ParentImageID    postgres.ColumnString
	RelationshipType postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ImageParentTableTable struct {
	imageParentTableTable

	EXCLUDED imageParentTableTable
}

// AS creates new ImageParentTableTable with assigned alias
func (a ImageParentTableTable) AS(alias string) *ImageParentTableTable {
	return newImageParentTableTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImageParentTableTable with assigned schema name
func (a ImageParentTableTable) FromSchema(schemaName string) *ImageParentTableTable {
	return newImageParentTableTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImageParentTableTable with assigned table prefix
func (a ImageParentTableTable) WithPrefix(prefix string) *ImageParentTableTable {
	return newImageParentTableTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImageParentTableTable with assigned table suffix
func (a ImageParentTableTable) WithSuffix(suffix string) *ImageParentTableTable {
	return newImageParentTableTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImageParentTableTable(schemaName, tableName, alias string) *ImageParentTableTable {
	return &ImageParentTableTable{
		imageParentTableTable: newImageParentTableTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newImageParentTableTableImpl("", "excluded", ""),
	}
}

func newImageParentTableTableImpl(schemaName, tableName, alias string) imageParentTableTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		ImageIDColumn          = postgres.StringColumn("image_id")
		ParentImageIDColumn    = postgres.StringColumn("parent_image_id")
		RelationshipTypeColumn = postgres.StringColumn("relationship_type")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		allColumns             = postgres.ColumnList{IDColumn, ImageIDColumn, ParentImageIDColumn, RelationshipTypeColumn, CreatedAtColumn}
		mutableColumns         = postgres.ColumnList{ImageIDColumn, ParentImageIDColumn, RelationshipTypeColumn, CreatedAtColumn}
		defaultColumns         = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return imageParentTableTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		ImageID:          ImageIDColumn,
		ParentImageID:    ParentImageIDColumn,
		RelationshipType: RelationshipTypeColumn,
		CreatedAt:        CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
