package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/ericls/imgdd/db"
	"github.com/ericls/imgdd/domainmodels"
	"github.com/ericls/imgdd/editing"
	"github.com/ericls/imgdd/graph/model"
	"github.com/ericls/imgdd/identity"
	"github.com/ericls/imgdd/image"
	"github.com/ericls/imgdd/storage"
	"github.com/ericls/imgdd/utils"
	"github.com/google/uuid"
)

// URL is the resolver for the url field.
func (r *imageResolver) URL(ctx context.Context, obj *model.Image) (string, error) {
	image := domainmodels.Image{
		Id:         obj.ID,
		Identifier: obj.Identifier,
		MIMEType:   obj.MIMEType,
	}
	loader := LoadersFor(ctx).StoredImagesByImageIdsLoader
	storedImages, err := loader.Load(ctx, obj.ID)
	if err != nil {
		return "", err
	}
	var externalIdentifiers []*domainmodels.ExternalImageIdentifier
	for _, storedImage := range storedImages {
		if storedImage == nil || storedImage.StorageDefinition == nil {
			continue
		}
		externalIdentifiers = append(externalIdentifiers, &domainmodels.ExternalImageIdentifier{
			StorageDefinitionIdentifier: storedImage.StorageDefinition.Identifier,
			FileIdentifier:              storedImage.FileIdentifier,
		})
	}
	return image.GetURL(r.ImageDomain, r.IsHttps(ctx), externalIdentifiers, r.DefaultURLFormat), nil
}

// Root is the resolver for the root field.
// Walks up the "base" parent chain to find the ultimate ancestor.
func (r *imageResolver) Root(ctx context.Context, obj *model.Image) (*model.Image, error) {
	lineage, err := r.Lineage(ctx, obj)
	if err != nil {
		return nil, err
	}
	// Lineage returns [root, ..., current]. If only current, no root.
	if len(lineage) <= 1 {
		return nil, nil
	}
	return lineage[0], nil
}

// Parent is the resolver for the parent field.
func (r *imageResolver) Parent(ctx context.Context, obj *model.Image) (*model.Image, error) {
	return LoadersFor(ctx).BaseParentByImageIdLoader.Load(ctx, obj.ID)
}

// Changes is the resolver for the changes field.
func (r *imageResolver) Changes(ctx context.Context, obj *model.Image) (*string, error) {
	if obj.RawChanges == "" || obj.RawChanges == "[]" || obj.RawChanges == "{}" {
		return nil, nil
	}
	return &obj.RawChanges, nil
}

// Lineage is the resolver for the lineage field.
// Returns the chain of ancestors from root to this image (inclusive),
// walking "base" parent relationships via the DAG table.
// Uses 3 queries total: ancestor IDs (recursive CTE), batch image fetch, batch relationship fetch.
func (r *imageResolver) Lineage(ctx context.Context, obj *model.Image) ([]*model.Image, error) {
	// 1. Get all ancestor IDs in one recursive CTE query
	ancestorIds, err := r.ImageRelRepo.GetAncestorIds(obj.ID)
	if err != nil {
		return nil, err
	}
	if len(ancestorIds) == 0 {
		return []*model.Image{obj}, nil
	}

	// 2. Batch fetch all ancestor images
	ancestors, err := r.ImageRepo.GetImagesByIds(ancestorIds)
	if err != nil {
		return nil, err
	}
	imageById := make(map[string]*domainmodels.Image, len(ancestors))
	for _, img := range ancestors {
		if img != nil {
			imageById[img.Id] = img
		}
	}

	// 3. Batch fetch relationships for all ancestors + current image
	allIds := append(ancestorIds, obj.ID)
	relsByImageId, err := r.ImageRelRepo.GetParentsByImageIds(allIds)
	if err != nil {
		return nil, err
	}

	// 4. Reconstruct the base-parent chain by walking from current image to root
	const maxDepth = 100
	chain := []*model.Image{obj}
	currentId := obj.ID
	visited := map[string]bool{obj.ID: true}
	for len(chain) < maxDepth {
		rels := relsByImageId[currentId]
		var baseParentId string
		for _, rel := range rels {
			if rel.RelationshipType == image.RelationshipTypeBase {
				baseParentId = rel.ParentImageId
				break
			}
		}
		if baseParentId == "" || visited[baseParentId] {
			break
		}
		parent, ok := imageById[baseParentId]
		if !ok || parent == nil {
			break
		}
		chain = append(chain, model.FromImage(parent))
		visited[baseParentId] = true
		currentId = baseParentId
	}

	// Reverse so root comes first
	for i, j := 0, len(chain)-1; i < j; i, j = i+1, j-1 {
		chain[i], chain[j] = chain[j], chain[i]
	}
	return chain, nil
}

// Revisions is the resolver for the revisions field.
func (r *imageResolver) Revisions(ctx context.Context, obj *model.Image) ([]*model.Image, error) {
	// TODO: Implement this method after we support revisions.
	return []*model.Image{}, nil
}

// StoredImages is the resolver for the storedImages field.
func (r *imageResolver) StoredImages(ctx context.Context, obj *model.Image) ([]*model.StoredImage, error) {
	loader := LoadersFor(ctx).StoredImagesByImageIdsLoader
	return loader.Load(ctx, obj.ID)
}

// CreatedBy is the resolver for the createdBy field.
func (r *imageResolver) CreatedBy(ctx context.Context, obj *model.Image) (*model.OrganizationUser, error) {
	if obj.CreatedById == "" {
		return nil, nil
	}
	return LoadersFor(ctx).OrganizationUserLoader.Load(ctx, obj.CreatedById)
}

// DeleteImage is the resolver for the deleteImage field.
func (r *mutationResolver) DeleteImage(ctx context.Context, input model.DeleteImageInput) (*model.DeleteImageResult, error) {
	if _, err := uuid.Parse(input.ID); err != nil {
		return nil, fmt.Errorf("image not found")
	}
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if img, err := r.ImageRepo.GetImageById(input.ID); err != nil {
		return nil, err
	} else if img == nil {
		return nil, fmt.Errorf("image not found")
	} else {
		createdBy := r.IdentityRepo.GetOrganizationUserById(img.CreatedById)
		if !currentUser.CanManage(createdBy) {
			return nil, fmt.Errorf("unauthorized")
		}
		// Block deletion if image has relationships (as parent or child)
		hasRels, err := r.ImageRelRepo.HasRelationships(input.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to check image relationships: %w", err)
		}
		if hasRels {
			return nil, fmt.Errorf("cannot delete image with edit relationships")
		}
		if err := r.ImageRepo.DeleteImageById(input.ID); err != nil {
			return nil, err
		} else {
			return &model.DeleteImageResult{ID: &input.ID}, nil
		}
	}
}

// ApplyWatermark is the resolver for the applyWatermark field.
func (r *mutationResolver) ApplyWatermark(ctx context.Context, input model.ApplyWatermarkInput) (*model.ApplyWatermarkResult, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	// Validate IDs
	if _, err := uuid.Parse(input.BaseImageID); err != nil {
		return nil, fmt.Errorf("base image not found")
	}
	if _, err := uuid.Parse(input.OverlayImageID); err != nil {
		return nil, fmt.Errorf("overlay image not found")
	}

	// Validate both images exist and are owned by the current user
	baseImage, err := r.ImageRepo.GetImageById(input.BaseImageID)
	if err != nil || baseImage == nil {
		return nil, fmt.Errorf("base image not found")
	}
	if baseImage.CreatedById != currentUser.Id {
		return nil, fmt.Errorf("unauthorized")
	}

	overlayImage, err := r.ImageRepo.GetImageById(input.OverlayImageID)
	if err != nil || overlayImage == nil {
		return nil, fmt.Errorf("overlay image not found")
	}
	if overlayImage.CreatedById != currentUser.Id {
		return nil, fmt.Errorf("unauthorized")
	}

	if input.Position == nil {
		return nil, fmt.Errorf("position is required")
	}

	// Map GraphQL anchor to editing anchor
	anchorMap := map[model.Anchor]editing.Anchor{
		model.AnchorTopLeft:     editing.AnchorTopLeft,
		model.AnchorTopRight:    editing.AnchorTopRight,
		model.AnchorBottomLeft:  editing.AnchorBottomLeft,
		model.AnchorBottomRight: editing.AnchorBottomRight,
		model.AnchorCenter:      editing.AnchorCenter,
	}
	anchor, ok := anchorMap[input.Anchor]
	if !ok {
		return nil, fmt.Errorf("invalid anchor: %s", input.Anchor)
	}

	c, err := editing.NewWatermarkChange(editing.WatermarkParams{
		OverlayImageID: input.OverlayImageID,
		Position:       editing.WatermarkPosition{X: input.Position.X, Y: input.Position.Y},
		Anchor:         anchor,
		Opacity:        input.Opacity,
		Scale:          input.Scale,
	})
	if err != nil {
		return nil, err
	}

	fetchImage := editing.NewFetchImageFunc(r.StoredImageRepo, r.StorageDefRepo, r.ImageMaxUploadBytes)
	result, err := editing.ApplyChangeSet(editing.ChangeSet{c}, input.BaseImageID, fetchImage)
	if err != nil {
		return nil, err
	}

	width, height, err := utils.GetImageDimensions(result.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to get result dimensions: %w", err)
	}

	// Find storage backend
	storageDefs, err := r.StorageDefRepo.ListStorageDefinitions()
	if err != nil {
		return nil, fmt.Errorf("failed to list storage definitions: %w", err)
	}
	var storageDef *domainmodels.StorageDefinition
	for _, def := range storageDefs {
		if def.IsEnabled {
			storageDef = def
			break
		}
	}
	if storageDef == nil {
		return nil, fmt.Errorf("no enabled storage backend")
	}

	storageInstance, err := storage.GetStorage(storageDef)
	if err != nil {
		return nil, fmt.Errorf("failed to get storage: %w", err)
	}

	// Create image and relationships in a single transaction
	tx, err := r.DBConn.Begin()
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	dbImageRepo, ok := r.ImageRepo.(db.DBRepo)
	if !ok {
		return nil, fmt.Errorf("image repo does not support transactions")
	}
	dbImageRelRepo, ok := r.ImageRelRepo.(db.DBRepo)
	if !ok {
		return nil, fmt.Errorf("image relationship repo does not support transactions")
	}
	txImageRepo, ok := dbImageRepo.WithTransaction(tx).(*image.DBImageRepo)
	if !ok {
		return nil, fmt.Errorf("image repo does not support transactions")
	}
	txImageRelRepo, ok := dbImageRelRepo.WithTransaction(tx).(*image.DBImageRelationshipRepo)
	if !ok {
		return nil, fmt.Errorf("image relationship repo does not support transactions")
	}

	newImage := domainmodels.Image{
		Identifier:      uuid.New().String(),
		Name:            baseImage.Name,
		ParentId:        baseImage.Id,
		Changes:         string(result.ChangesJSON),
		CreatedById:     currentUser.Id,
		MIMEType:        result.MIMEType,
		NominalWidth:    width,
		NominalHeight:   height,
		NominalByteSize: int32(len(result.Bytes)),
	}

	storedImage, err := txImageRepo.CreateAndSaveUploadedImage(&newImage, result.MIMEType, result.Bytes, storageDef.Id, storageInstance.Save)
	if err != nil {
		return nil, fmt.Errorf("failed to save result image: %w", err)
	}

	newImageId := storedImage.Image.Id
	if _, err := txImageRelRepo.CreateRelationship(newImageId, input.BaseImageID, image.RelationshipTypeBase); err != nil {
		return nil, fmt.Errorf("failed to create base relationship: %w", err)
	}
	if _, err := txImageRelRepo.CreateRelationship(newImageId, input.OverlayImageID, image.RelationshipTypeOverlay); err != nil {
		return nil, fmt.Errorf("failed to create overlay relationship: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &model.ApplyWatermarkResult{
		Image: model.FromImage(storedImage.Image),
	}, nil
}

// ApplyBlur is the resolver for the applyBlur field.
func (r *mutationResolver) ApplyBlur(ctx context.Context, input model.ApplyBlurInput) (*model.ApplyBlurResult, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	if _, err := uuid.Parse(input.BaseImageID); err != nil {
		return nil, fmt.Errorf("base image not found")
	}

	baseImage, err := r.ImageRepo.GetImageById(input.BaseImageID)
	if err != nil || baseImage == nil {
		return nil, fmt.Errorf("base image not found")
	}
	if baseImage.CreatedById != currentUser.Id {
		return nil, fmt.Errorf("unauthorized")
	}

	if input.Region == nil {
		return nil, fmt.Errorf("region is required")
	}

	c, err := editing.NewBlurChange(editing.BlurParams{
		Region: editing.BlurRegion{
			X1: input.Region.X1,
			Y1: input.Region.Y1,
			X2: input.Region.X2,
			Y2: input.Region.Y2,
		},
		Radius: input.Radius,
	})
	if err != nil {
		return nil, err
	}

	fetchImage := editing.NewFetchImageFunc(r.StoredImageRepo, r.StorageDefRepo, r.ImageMaxUploadBytes)
	result, err := editing.ApplyChangeSet(editing.ChangeSet{c}, input.BaseImageID, fetchImage)
	if err != nil {
		return nil, err
	}

	width, height, err := utils.GetImageDimensions(result.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to get result dimensions: %w", err)
	}

	storageDefs, err := r.StorageDefRepo.ListStorageDefinitions()
	if err != nil {
		return nil, fmt.Errorf("failed to list storage definitions: %w", err)
	}
	var storageDef *domainmodels.StorageDefinition
	for _, def := range storageDefs {
		if def.IsEnabled {
			storageDef = def
			break
		}
	}
	if storageDef == nil {
		return nil, fmt.Errorf("no enabled storage backend")
	}

	storageInstance, err := storage.GetStorage(storageDef)
	if err != nil {
		return nil, fmt.Errorf("failed to get storage: %w", err)
	}

	tx, err := r.DBConn.Begin()
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	dbImageRepo, ok := r.ImageRepo.(db.DBRepo)
	if !ok {
		return nil, fmt.Errorf("image repo does not support transactions")
	}
	txImageRepo, ok := dbImageRepo.WithTransaction(tx).(*image.DBImageRepo)
	if !ok {
		return nil, fmt.Errorf("image repo does not support transactions")
	}

	dbImageRelRepo, ok := r.ImageRelRepo.(db.DBRepo)
	if !ok {
		return nil, fmt.Errorf("image relationship repo does not support transactions")
	}
	txImageRelRepo, ok := dbImageRelRepo.WithTransaction(tx).(*image.DBImageRelationshipRepo)
	if !ok {
		return nil, fmt.Errorf("image relationship repo does not support transactions")
	}

	newImage := domainmodels.Image{
		Identifier:      uuid.New().String(),
		Name:            baseImage.Name,
		ParentId:        baseImage.Id,
		Changes:         string(result.ChangesJSON),
		CreatedById:     currentUser.Id,
		MIMEType:        result.MIMEType,
		NominalWidth:    width,
		NominalHeight:   height,
		NominalByteSize: int32(len(result.Bytes)),
	}

	storedImage, err := txImageRepo.CreateAndSaveUploadedImage(&newImage, result.MIMEType, result.Bytes, storageDef.Id, storageInstance.Save)
	if err != nil {
		return nil, fmt.Errorf("failed to save result image: %w", err)
	}

	newImageId := storedImage.Image.Id
	if _, err := txImageRelRepo.CreateRelationship(newImageId, input.BaseImageID, image.RelationshipTypeBase); err != nil {
		return nil, fmt.Errorf("failed to create base relationship: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &model.ApplyBlurResult{
		Image: model.FromImage(storedImage.Image),
	}, nil
}

// Image is the resolver for the image field.
func (r *viewerResolver) Image(ctx context.Context, obj *model.Viewer, id string) (*model.Image, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	if _, err := uuid.Parse(id); err != nil {
		return nil, fmt.Errorf("image not found")
	}

	img, err := r.ImageRepo.GetImageById(id)
	if err != nil || img == nil {
		return nil, fmt.Errorf("image not found")
	}
	createdBy := r.IdentityRepo.GetOrganizationUserById(img.CreatedById)
	if !currentUser.CanManage(createdBy) {
		return nil, fmt.Errorf("unauthorized")
	}

	return model.FromImage(img), nil
}

// Images is the resolver for the images field.
func (r *viewerResolver) Images(ctx context.Context, obj *model.Viewer, orderBy *model.ImageOrderByInput, filters *model.ImageFilterInput, after *string, before *string) (*model.ImagesResult, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized")
	}
	if after != nil && before != nil {
		return nil, fmt.Errorf("only one of after or before can be specified")
	}
	if filters == nil {
		filters = &model.ImageFilterInput{}
	}
	if !currentUser.IsSiteOwner() {
		// TODO: make permission checks more structured.
		if filters.CreatedBy == nil {
			filters.CreatedBy = &currentUser.Id
		}
	}

	if filters.CreatedBy != nil {
		filterByUser := r.IdentityRepo.GetOrganizationUserById(*filters.CreatedBy)
		if filterByUser == nil {
			return nil, fmt.Errorf("unathorized")
		}
		if !currentUser.CanManage(filterByUser) {
			return nil, fmt.Errorf("unauthorized")
		}
	}

	paginator := model.MakeImagePaginator(orderBy, filters)
	listImagesFilters := image.FromPaginationFilter(paginator.Filter)
	count, err := r.ImageRepo.CountImages(listImagesFilters)
	if err != nil {
		return nil, err
	}

	if err = paginator.ContributeCursorStringToFilter(after, true); err != nil {
		return nil, err
	}
	if err = paginator.ContributeCursorStringToFilter(before, false); err != nil {
		return nil, err
	}

	listImagesFiltersWithCursor := image.FromPaginationFilter(paginator.Filter)
	var listImagesOrdering *image.ListImagesOrdering
	if before != nil {
		listImagesOrdering = image.FromPaginationOrder(paginator.Order.Reverse())
	} else {
		listImagesOrdering = image.FromPaginationOrder(paginator.Order)
	}

	listImageResult, err := r.ImageRepo.ListImages(listImagesFilters, listImagesFiltersWithCursor, listImagesOrdering, before != nil)
	if err != nil {
		return nil, err
	}
	cursorEncoder := model.CursorEncoder(func(i *domainmodels.Image) string {
		return paginator.Order.EncodeCursor(i)
	})
	result := model.FromListImageResult(&listImageResult, count, cursorEncoder)
	return result, nil
}

// Image returns ImageResolver implementation.
func (r *Resolver) Image() ImageResolver { return &imageResolver{r} }

type imageResolver struct{ *Resolver }
