package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/ericls/imgdd/graph/model"
	imgddimage "github.com/ericls/imgdd/image"
	"github.com/google/uuid"
)

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	return &model.Viewer{}, nil
}

// PublicImage is the resolver for the publicImage field.
func (r *queryResolver) PublicImage(ctx context.Context, id string) (*model.Image, error) {
	if _, err := uuid.Parse(id); err != nil {
		return nil, fmt.Errorf("image not found")
	}

	img, err := r.ImageRepo.GetImageById(id)
	if err != nil || img == nil {
		return nil, fmt.Errorf("image not found")
	}
	if img.CreatedById != "" && img.CreatedById != imgddimage.ZeroUUID.String() {
		return nil, nil
	}

	return model.FromImage(img), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
