package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/ericls/imgdd/graph/model"
	"github.com/ericls/imgdd/identity"
)

// HasPermission is the resolver for the hasPermission field.
func (r *viewerResolver) HasPermission(ctx context.Context, obj *model.Viewer, permission model.PermissionNameEnum) (bool, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return false, nil
	}
	if permission == model.PermissionName_SiteOwnerAccess {
		if currentUser.IsSiteOwner() {
			return true, nil
		}
	}
	if permission == model.PermissionName_AdminAccess {
		if currentUser.HasAdminAccess() {
			return true, nil
		}
	}
	return false, nil
}
