package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"imgdd/graph/model"
	"imgdd/identity"
)

// HasPermission is the resolver for the hasPermission field.
func (r *viewerResolver) HasPermission(ctx context.Context, obj *model.Viewer, permission model.PermissionNameEnum) (bool, error) {
	currentUser := identity.GetCurrentOrganizationUser(r.ContextUserManager, ctx)
	if currentUser == nil {
		return false, nil
	}
	if permission == model.PermissionName_SiteOwnerAccess {
		for _, role := range currentUser.Roles {
			if role.Key == "site_owner" {
				return true, nil
			}
		}
	}
	if permission == model.PermissionName_AdminAccess {
		for _, role := range currentUser.Roles {
			if role.Key == "admin" || role.Key == "owner" || role.Key == "site_owner" {
				return true, nil
			}
		}
	}
	return false, nil
}
