package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"imgdd/graph/model"
)

// StorageDefinitions is the resolver for the storageDefinitions field.
func (r *viewerResolver) StorageDefinitions(ctx context.Context, obj *model.Viewer) ([]*model.StorageDefinition, error) {
	panic(fmt.Errorf("not implemented: StorageDefinitions - storageDefinitions"))
}
