package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/ericls/imgdd/graph/model"
)

// AllUsers is the resolver for the allUsers field.
func (r *viewerResolver) AllUsers(ctx context.Context, obj *model.Viewer, limit *int, offset *int, search *string) ([]*model.User, error) {
	// Set default values for pagination
	defaultLimit := 100
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}
	if offset == nil {
		offset = &defaultOffset
	}

	// Validate limit to prevent excessive queries
	if *limit > 1000 {
		return nil, fmt.Errorf("limit cannot exceed 1000")
	}
	if *limit < 0 {
		return nil, fmt.Errorf("limit must be non-negative")
	}
	if *offset < 0 {
		return nil, fmt.Errorf("offset must be non-negative")
	}

	// Get users from repository
	domainUsers := r.IdentityRepo.GetAllUsers(*limit, *offset, search)
	if domainUsers == nil {
		return []*model.User{}, nil
	}

	// Convert domain models to GraphQL models
	users := make([]*model.User, len(domainUsers))
	for i, domainUser := range domainUsers {
		users[i] = model.FromIdentityUser(domainUser)
	}

	return users, nil
}
