package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/ericls/imgdd/graph/model"
)

// ID is the resolver for the id field.
func (r *viewerResolver) ID(ctx context.Context, obj *model.Viewer) (string, error) {
	return "viewer", nil
}

// OrganizationUser is the resolver for the organizationUser field.
func (r *viewerResolver) OrganizationUser(ctx context.Context, obj *model.Viewer) (*model.OrganizationUser, error) {
	authInfo := r.ContextUserManager.GetAuthenticationInfo(ctx)
	var orgUser *model.OrganizationUser
	if authInfo != nil && authInfo.AuthorizedUser != nil {
		orgUser = model.FromIdentityOrganizationUser(authInfo.AuthorizedUser.OrganizationUser)
	}
	return orgUser, nil
}

// OrganizationUserByID is the resolver for the organizationUserById field.
func (r *viewerResolver) OrganizationUserByID(ctx context.Context, obj *model.Viewer, id string) (*model.OrganizationUser, error) {
	return LoadersFor(ctx).OrganizationUserLoader.Load(ctx, id)
}

// UploadLimitBytes is the resolver for the uploadLimitBytes field.
// Returns the effective upload limit for the current viewer: guest limit for
// unauthenticated requests, per-user override (capped at global max) for
// authenticated requests, or the global max as the default.
func (r *viewerResolver) UploadLimitBytes(ctx context.Context, obj *model.Viewer) (int, error) {
	baseLimit := r.ImageMaxUploadBytes
	if r.GuestImageMaxUploadBytes > 0 {
		baseLimit = r.GuestImageMaxUploadBytes
	}
	effectiveLimit := baseLimit
	authInfo := r.ContextUserManager.GetAuthenticationInfo(ctx)
	if authInfo != nil && authInfo.AuthorizedUser != nil {
		if ou := authInfo.AuthorizedUser.OrganizationUser; ou != nil && ou.UploadLimitBytes != nil {
			effectiveLimit = *ou.UploadLimitBytes
			if effectiveLimit > r.ImageMaxUploadBytes {
				effectiveLimit = r.ImageMaxUploadBytes
			}
		}
	}
	return int(effectiveLimit), nil
}

// Viewer returns ViewerResolver implementation.
func (r *Resolver) Viewer() ViewerResolver { return &viewerResolver{r} }

type viewerResolver struct{ *Resolver }
