// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserWithOrganizationInput struct {
	UserEmail        string `json:"userEmail"`
	UserPassword     string `json:"userPassword"`
	OrganizationName string `json:"organizationName"`
}

type ViewerResult struct {
	Viewer *Viewer `json:"viewer"`
}
