//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/google/uuid"
)

type OrganizationUserTable struct {
	ID               uuid.UUID `sql:"primary_key"`
	OrganizationID   uuid.UUID
	UserID           uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UploadLimitBytes *int64
}
