name: Backend test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:27.5.1-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run tests with Docker
        run: go test -v ./...
