name: Build & Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Up QEMU (for Multi-Arch Builds)
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git Metadata
        id: git
        run: |
          echo "GIT_REV=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/imgdd:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/imgdd:${{ env.VERSION }}
          build-args: |
            GIT_REV=${{ env.GIT_REV }}
            GIT_HASH=${{ env.GIT_HASH }}
          platforms: linux/amd64,linux/arm64
